-- =============================================
-- Student Management System - Initial Data
-- =============================================
-- NOTE: These BCrypt hashes are placeholders.
-- Run the BCryptGenerator utility or replace with
-- real hashes before using in production.
-- =============================================

-- 1. 用户数据（BCrypt hashes generated by Python bcrypt, rounds=10）
-- Passwords: admin/admin123, teacher01/teacher123, student01/student123
INSERT INTO sys_user (username, password, real_name, role, phone, email, status) VALUES
('admin', '$2b$10$.ydolp/Sb/XXpxx.DttwMOBivAqtedei.F0oEWKhm3i8VMB13jBRq', '系统管理员', 'ADMIN', '13800000001', 'admin@school.edu.cn', 1),
('teacher01', '$2b$10$wTNXV3uJYPdine80197aieRB.aSLacTdXTDkNsb0DEQvnNbm2IVrW', '张教授', 'TEACHER', '13800000002', 'zhang@school.edu.cn', 1),
('teacher02', '$2b$10$wTNXV3uJYPdine80197aieRB.aSLacTdXTDkNsb0DEQvnNbm2IVrW', '李教授', 'TEACHER', '13800000003', 'li@school.edu.cn', 1),
('student01', '$2b$10$EQLg9O1LOmg80h0hBCnhVu/2mXU2r03PUienucFXA./lkqJfTIKty', '王同学', 'STUDENT', '13900000001', 'wang@stu.school.edu.cn', 1),
('student02', '$2b$10$EQLg9O1LOmg80h0hBCnhVu/2mXU2r03PUienucFXA./lkqJfTIKty', '赵同学', 'STUDENT', '13900000002', 'zhao@stu.school.edu.cn', 1),
('student03', '$2b$10$EQLg9O1LOmg80h0hBCnhVu/2mXU2r03PUienucFXA./lkqJfTIKty', '刘同学', 'STUDENT', '13900000003', 'liu@stu.school.edu.cn', 1);

-- 2. 院系数据
INSERT INTO department (dept_no, dept_name, dept_head) VALUES
('CS', '计算机科学与技术学院', '王院长'),
('MATH', '数学与统计学院', '李院长'),
('ENG', '外国语学院', '陈院长');

-- 3. 专业数据
INSERT INTO major (major_no, major_name, dept_id) VALUES
('CS01', '计算机科学与技术', 1),
('CS02', '软件工程', 1),
('CS03', '数据科学与大数据技术', 1),
('MATH01', '数学与应用数学', 2),
('ENG01', '英语', 3);

-- 4. 班级数据
INSERT INTO `class` (class_no, class_name, major_id, grade) VALUES
('CS2101', '计算机2101班', 1, 2021),
('CS2102', '计算机2102班', 1, 2021),
('SE2101', '软件2101班', 2, 2021),
('DS2101', '大数据2101班', 3, 2021);

-- 5. 教师数据
INSERT INTO teacher (teacher_no, name, gender, title, phone, email, dept_id, user_id) VALUES
('T001', '张教授', 'M', '教授', '13800000002', 'zhang@school.edu.cn', 1, 2),
('T002', '李教授', 'F', '副教授', '13800000003', 'li@school.edu.cn', 1, 3);

-- 6. 学生数据
INSERT INTO student (student_no, name, gender, birth_date, phone, address, enrollment_year, political_status, class_id, user_id) VALUES
('2021001', '王同学', 'M', '2002-05-15', '13900000001', '北京市海淀区', 2021, '共青团员', 1, 4),
('2021002', '赵同学', 'F', '2002-08-22', '13900000002', '上海市浦东新区', 2021, '共青团员', 1, 5),
('2021003', '刘同学', 'M', '2001-12-10', '13900000003', '广州市天河区', 2021, '共青团员', 2, 6);

-- 7. 课程数据
INSERT INTO course (course_no, course_name, credit, total_hours, course_type, dept_id, description) VALUES
('CS101', '数据结构与算法', 4.0, 64, '必修', 1, '学习基本数据结构和算法设计与分析'),
('CS102', '操作系统原理', 3.5, 56, '必修', 1, '学习操作系统的基本概念与原理'),
('CS201', '数据库系统概论', 3.0, 48, '必修', 1, '学习关系数据库理论与SQL语言'),
('CS301', '人工智能导论', 2.5, 40, '选修', 1, '人工智能基本概念与应用'),
('MATH101', '高等数学A', 5.0, 80, '必修', 2, '高等数学基础课程');

-- 8. 开课数据
INSERT INTO course_offering (course_id, teacher_id, semester, max_capacity, current_count, schedule, classroom, status) VALUES
(1, 1, '2025S1', 60, 2, '周一 1-2节', '教1-301', 'OPEN'),
(2, 1, '2025S1', 45, 0, '周二 3-4节', '教1-405', 'OPEN'),
(3, 2, '2025S1', 50, 0, '周三 5-6节', '教2-201', 'OPEN'),
(4, 2, '2025S1', 30, 0, '周四 7-8节', '教3-102', 'OPEN'),
(5, 1, '2025S1', 80, 0, '周五 1-2节', '教1-101', 'OPEN');

-- 9. 选课记录
INSERT INTO enrollment (student_id, offering_id, status) VALUES
(1, 1, 'ENROLLED'),
(2, 1, 'ENROLLED');
